framework:
    workflows:
        deliberation:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'etat'
            supports:
                - App\Entity\Deliberation
            initial_marking: cree
            places:
                - cree
                - valide
                - rejete
            transitions:
                validation:
                    from: cree
                    to: valide
                rejet:
                    from: cree
                    to: rejete
        
        preinscription:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'etat'
            supports:
                - App\Entity\Preinscription
            initial_marking: attente_validation
            places:
                - attente_validation
                - rejete
                - attente_paiement
                - valide
                - attente_inscription
                - inscription
                - attente_informations
                - ajourne_inscription
                - paiement_confirmation
            transitions:
                validation:
                    from: attente_validation
                    to: attente_paiement
                rejet:
                    from: attente_validation
                    to: rejete
                paiement:
                    from: attente_paiement
                    to: valide
                creation_inscription:
                    from: valide
                    to: attente_inscription
                rejet_inscription:
                    from: valide
                    to: ajourne_inscription
                inscription:
                    from: attente_inscription
                    to: inscription
                paiement_confirmation:
                    from: attente_paiement
                    to: paiement_confirmation
                attente_information:
                    from: attente_validation
                    to: attente_informations

        niveau_etudiant:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'etat'
            supports:
                - App\Entity\NiveauEtudiant
            initial_marking: attente_validation
            places:
                - attente_validation
                - rejete
                - attente_paiement
                - valide
            transitions:
                validation:
                    from: attente_validation
                    to: attente_paiement
                rejet:
                    from: attente_validation
                    to: rejete
                paiement:
                    from: attente_paiement
                    to: valide


        inscription:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'etat'
            supports:
                - App\Entity\Inscription
            initial_marking: attente_echeancier
            places:
                - attente_echeancier
                - echeance_soumis
                - valide
                - rejete
                - solde
            transitions:
                soumission:
                    from: attente_echeancier
                    to: echeance_soumis
                rejet:
                    from: echeance_soumis
                    to: rejete
                retour:
                    from: rejete
                    to: echeance_soumis
                valider:
                    from: echeance_soumis
                    to: valide
                paiement:
                    from: valide
                    to: solde

        
               

